In [11]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn import metrics
data = pd.read_csv('iris.csv')

data.head(10)
data.shape

(150, 5)

In [12]:
X = data.drop('Name', axis=1)
y = data['Name']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)
logr = linear_model.LogisticRegression()
logr.fit(X_train,y_train)

#predict if tumor is cancerous where the size is 3.46mm:
predicted = logr.predict([[5.0,3.6,1.4,0.2]])

print(predicted)
y_pred = logr.predict(X_test)
print(X_test,y_pred )

['Iris-setosa']
     SepalLength  SepalWidth  PetalLength  PetalWidth
74           6.4         2.9          4.3         1.3
13           4.3         3.0          1.1         0.1
58           6.6         2.9          4.6         1.3
111          6.4         2.7          5.3         1.9
89           5.5         2.5          4.0         1.3
108          6.7         2.5          5.8         1.8
96           5.7         2.9          4.2         1.3
90           5.5         2.6          4.4         1.2
50           7.0         3.2          4.7         1.4
68           6.2         2.2          4.5         1.5
91           6.1         3.0          4.6         1.4
93           5.0         2.3          3.3         1.0
2            4.7         3.2          1.3         0.2
80           5.5         2.4          3.8         1.1
88           5.6         3.0          4.1         1.3
94           5.6         2.7          4.2         1.3
42           4.4         3.2          1.3         0.2
106         

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [9]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 8  0  0]
 [ 0 11  0]
 [ 0  1 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         8
Iris-versicolor       0.92      1.00      0.96        11
 Iris-virginica       1.00      0.91      0.95        11

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30

